steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/email-parser:$SHORT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/email-parser:$SHORT_SHA"]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud run deploy email-parser \
        --image gcr.io/$PROJECT_ID/email-parser:$SHORT_SHA \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated
images:
- "gcr.io/$PROJECT_ID/email-parser:$SHORT_SHA"
